//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EverestFoodCafe.Domain.Concrete
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime EntryDate { get; set; }
        public string Comments { get; set; }
        public int Rating { get; set; }
        public int DishID { get; set; }
    
        public virtual Dish Dish { get; set; }
    }
}
